package com.example.smartdisplay

data class ClockStyleDef(
    val name: String,
    val category: String,
    val isAnalog: Boolean,
    val fontFamily: String = "default",
    val textColorHex: String = "#FFFFFF",
    val accentColorHex: String = "#D0BCFF",
    val secondsColorHex: String = "#FF6B6B",
    val backgroundColorHex: String = "#000000",
    val backgroundOpacity: Float = 0.5f,
    val showSeconds: Boolean = true,
    val showDate: Boolean = true,
    val dateFormat: String = "EEEE, d MMMM",
    val timeFontMultiplier: Float = 1.0f,
    val fontWeight: Int = 300,
    val letterSpacing: Float = 4f,
    val showAmPm: Boolean = false,
    val analogTickColorHex: String = "#FFFFFF",
    val analogHandColorHex: String = "#FFFFFF",
    val analogShowNumbers: Boolean = true,
    val analogHourHandWidth: Float = 5f,
    val analogMinuteHandWidth: Float = 3f,
    val analogSecondHandWidth: Float = 1.5f,
    val showBorderGlow: Boolean = false,
    val showGradientText: Boolean = false,
    val useBoldTime: Boolean = false,
    val useItalicTime: Boolean = false,
    val dateAboveTime: Boolean = false,
    val description: String = ""
)

object ClockStyles {
    val all: List<ClockStyleDef> = listOf(
        /* ===== DIGITAL CLASSIC (0-9) ===== */
        ClockStyleDef("Classico Bianco", "Digitale", false,
            description = "Ore:minuti bianchi su sfondo nero, formato 24h"),
        ClockStyleDef("Classico Chiaro", "Digitale", false,
            textColorHex = "#E8E8E8", accentColorHex = "#BB86FC",
            description = "Variante soft del classico bianco"),
        ClockStyleDef("Classico con secondi", "Digitale", false,
            secondsColorHex = "#00E5FF",
            description = "Secondi in ciano brillante"),
        ClockStyleDef("Classico AM/PM", "Digitale", false,
            showAmPm = true, dateFormat = "MMM d, yyyy",
            description = "Formato 12h con AM/PM"),
        ClockStyleDef("Serif Elegante", "Digitale", false,
            fontFamily = "serif", fontWeight = 200, letterSpacing = 6f,
            description = "Font serif, spaziatura ampia, leggero"),
        ClockStyleDef("Monospace Tech", "Digitale", false,
            fontFamily = "monospace", fontWeight = 400, letterSpacing = 2f,
            secondsColorHex = "#00FF88",
            description = "Font monospace, stile tech, secondi verdi"),
        ClockStyleDef("Data in alto", "Digitale", false,
            dateAboveTime = true, dateFormat = "EEEE, d MMMM",
            description = "Data sopra l'ora"),
        ClockStyleDef("Senza secondi", "Digitale", false,
            showSeconds = false,
            description = "Solo ore e minuti, senza secondi"),
        ClockStyleDef("Senza data", "Digitale", false,
            showDate = false,
            description = "Solo ora, senza data"),
        ClockStyleDef("Compatto", "Digitale", false,
            showSeconds = true, showDate = true, fontWeight = 600, letterSpacing = 1f,
            description = "Font semibold, spaziatura ridotta"),

        /* ===== DIGITAL COLOR (10-19) ===== */
        ClockStyleDef("Azzurro", "Colore", false,
            textColorHex = "#4FC3F7", accentColorHex = "#0288D1",
            description = "Testo azzurro, accenti blu scuro"),
        ClockStyleDef("Viola", "Colore", false,
            textColorHex = "#CE93D8", accentColorHex = "#7B1FA2",
            description = "Testo viola chiaro, accenti viola scuro"),
        ClockStyleDef("Verde", "Colore", false,
            textColorHex = "#81C784", accentColorHex = "#2E7D32",
            description = "Testo verde chiaro, accenti verde scuro"),
        ClockStyleDef("Rosso", "Colore", false,
            textColorHex = "#EF5350", accentColorHex = "#C62828",
            secondsColorHex = "#FFAB00",
            description = "Testo rosso, accenti rosso scuro"),
        ClockStyleDef("Arancione", "Colore", false,
            textColorHex = "#FFB74D", accentColorHex = "#E65100",
            description = "Arancione caldo"),
        ClockStyleDef("Rosa", "Colore", false,
            textColorHex = "#F48FB1", accentColorHex = "#AD1457",
            description = "Rosa tenue"),
        ClockStyleDef("Ciano notte", "Colore", false,
            textColorHex = "#80DEEA", accentColorHex = "#00838F",
            backgroundColorHex = "#0D1117",
            description = "Ciano su sfondo scuro notte"),
        ClockStyleDef("Oro", "Colore", false,
            textColorHex = "#FFD54F", accentColorHex = "#FF8F00",
            backgroundColorHex = "#1A1A1A",
            description = "Oro su sfondo scuro"),
        ClockStyleDef("Arcobaleno", "Colore", false,
            showGradientText = true,
            description = "Effetto gradiente arcobaleno sul testo"),
        ClockStyleDef("Lavanda", "Colore", false,
            textColorHex = "#E1BEE7", accentColorHex = "#6A1B9A",
            backgroundColorHex = "#1A1A2E",
            description = "Lavanda su sfondo blu scuro"),

        /* ===== DIGITAL MODERN (20-29) ===== */
        ClockStyleDef("Minimal Light", "Moderno", false,
            textColorHex = "#333333", backgroundColorHex = "#F5F5F5",
            showSeconds = false, fontWeight = 100, letterSpacing = 8f,
            description = "Scuro su sfondo chiaro, minimal"),
        ClockStyleDef("Minimal Dark", "Moderno", false,
            fontWeight = 100, letterSpacing = 8f, showSeconds = false,
            description = "Bianco su nero, sottilissimo"),
        ClockStyleDef("Neon Glow", "Moderno", false,
            textColorHex = "#00FFAA", accentColorHex = "#00FFAA",
            secondsColorHex = "#FF00AA", showBorderGlow = true,
            description = "Effetto neon glow verde/rosa"),
        ClockStyleDef("Digital Bold", "Moderno", false,
            fontWeight = 900, letterSpacing = 4f,
            description = "Grassetto, impattante"),
        ClockStyleDef("Thin Elegance", "Moderno", false,
            fontFamily = "serif", fontWeight = 100, letterSpacing = 10f,
            showSeconds = false,
            description = "Serif sottile, spaziatura estrema"),
        ClockStyleDef("Wide Spacing", "Moderno", false,
            fontWeight = 300, letterSpacing = 12f, showSeconds = false,
            description = "Spaziatura molto ampia"),
        ClockStyleDef("Mono Data", "Moderno", false,
            fontFamily = "monospace", dateFormat = "yyyy.MM.dd",
            description = "Monospace con data in formato ISO"),
        ClockStyleDef("No Colon", "Moderno", false,
            fontFamily = "monospace", fontWeight = 300, letterSpacing = 0f,
            showSeconds = false,
            description = "Monospace senza spaziatura, stile digitale puro"),
        ClockStyleDef("Glow Accent", "Moderno", false,
            accentColorHex = "#FFD700", showBorderGlow = true,
            description = "Bagliore dorato attorno all'orologio"),
        ClockStyleDef("Morph", "Moderno", false,
            fontWeight = 300, letterSpacing = 6f, dateFormat = "d MMMM yyyy",
            description = "Stile moderno e pulito"),

        /* ===== ANALOG CLASSIC (30-39) ===== */
        ClockStyleDef("Analogico Classico", "Analogico", true,
            analogShowNumbers = true,
            description = "Analogo tradizionale con numeri e lancette"),
        ClockStyleDef("Analogico Senza numeri", "Analogico", true,
            analogShowNumbers = false,
            description = "Solo tacche, senza numeri"),
        ClockStyleDef("Analogico Sottile", "Analogico", true,
            analogHourHandWidth = 3f, analogMinuteHandWidth = 2f,
            analogShowNumbers = true,
            description = "Lancette sottili ed eleganti"),
        ClockStyleDef("Analogico Secondi rossi", "Analogico", true,
            secondsColorHex = "#FF1744", analogSecondHandWidth = 2f,
            description = "Lancetta secondi in rosso vivo"),
        ClockStyleDef("Analogico Minimal", "Analogico", true,
            analogShowNumbers = false, analogHandColorHex = "#BB86FC",
            analogTickColorHex = "#BB86FC",
            description = "Minimal, viola, senza numeri"),
        ClockStyleDef("Analogico Grande", "Analogico", true,
            analogHourHandWidth = 7f, analogMinuteHandWidth = 4f,
            analogShowNumbers = true,
            description = "Lancette spesse e visibili"),
        ClockStyleDef("Analogico Oro", "Analogico", true,
            analogHandColorHex = "#FFD700", analogTickColorHex = "#FFD700",
            accentColorHex = "#FFD700", backgroundColorHex = "#1A1A1A",
            description = "Lancette oro su sfondo scuro"),
        ClockStyleDef("Analogico Azzurro", "Analogico", true,
            analogHandColorHex = "#4FC3F7", analogTickColorHex = "#4FC3F7",
            accentColorHex = "#4FC3F7",
            description = "Lancette azzurre"),
        ClockStyleDef("Analogico Dots", "Analogico", true,
            analogShowNumbers = false, analogTickColorHex = "#FFD54F",
            analogHandColorHex = "#FFD54F",
            description = "Punti invece di tacche, stile moderno"),
        ClockStyleDef("Analogico Night", "Analogico", true,
            analogHandColorHex = "#888888", analogTickColorHex = "#666666",
            showSeconds = false, backgroundColorHex = "#0A0A0A",
            description = "Versione notturna attenuata"),

        /* ===== ANALOG MODERN (40-49) ===== */
        ClockStyleDef("Analogico Glow", "Analogico moderno", true,
            analogHandColorHex = "#00E5FF", analogTickColorHex = "#00E5FF",
            showBorderGlow = true,
            description = "Effetto glow ciano"),
        ClockStyleDef("Analogico Gemelli", "Analogico moderno", true,
            analogHandColorHex = "#E040FB", analogTickColorHex = "#FFFFFF",
            showBorderGlow = true, backgroundColorHex = "#1A0033",
            description = "Lancette viola su sfondo scuro, bagliore"),
        ClockStyleDef("Analogico Polar", "Analogico moderno", true,
            analogHandColorHex = "#FFFFFF", analogTickColorHex = "#B0BEC5",
            backgroundColorHex = "#37474F", analogShowNumbers = true,
            description = "Tema polare, grigio-blu"),
        ClockStyleDef("Analogico Sunset", "Analogico moderno", true,
            analogHandColorHex = "#FF7043", analogTickColorHex = "#FFAB91",
            backgroundColorHex = "#1A0A00",
            description = "Tramonto, arancio su scuro"),
        ClockStyleDef("Analogico Oceano", "Analogico moderno", true,
            analogHandColorHex = "#26C6DA", analogTickColorHex = "#80DEEA",
            backgroundColorHex = "#001F2A",
            description = "Oceano, blu profondo"),
        ClockStyleDef("Analogico Foresta", "Analogico moderno", true,
            analogHandColorHex = "#66BB6A", analogTickColorHex = "#A5D6A7",
            backgroundColorHex = "#002200",
            description = "Foresta, verde su scuro"),
        ClockStyleDef("Analogico Lava", "Analogico moderno", true,
            analogHandColorHex = "#FF1744", analogTickColorHex = "#FF9100",
            backgroundColorHex = "#1A0000",
            description = "Lava, rosso/arancio su nero"),
        ClockStyleDef("Analogico Bianco e nero", "Analogico moderno", true,
            analogHandColorHex = "#000000", analogTickColorHex = "#000000",
            backgroundColorHex = "#FFFFFF", analogShowNumbers = true,
            description = "Lancette nere su sfondo bianco"),
        ClockStyleDef("Analogico Rosa", "Analogico moderno", true,
            analogHandColorHex = "#F06292", analogTickColorHex = "#F48FB1",
            backgroundColorHex = "#1A0011",
            description = "Rosa su sfondo scuro"),
        ClockStyleDef("Analogico Menta", "Analogico moderno", true,
            analogHandColorHex = "#69F0AE", analogTickColorHex = "#B9F6CA",
            backgroundColorHex = "#002211",
            description = "Menta verde su sfondo scuro"),

        /* ===== THEMED (50-59) ===== */
        ClockStyleDef("Tramonto", "Tema", false,
            textColorHex = "#FF6F00", accentColorHex = "#FF3D00",
            secondsColorHex = "#FFD600", backgroundColorHex = "#1A0033",
            description = "Caldo tramonto viola/arancio"),
        ClockStyleDef("Oceano", "Tema", false,
            textColorHex = "#00B4D8", accentColorHex = "#0077B6",
            secondsColorHex = "#90E0EF", backgroundColorHex = "#03045E",
            description = "Blu oceano profondo"),
        ClockStyleDef("Foresta", "Tema", false,
            textColorHex = "#A5D6A7", accentColorHex = "#2E7D32",
            secondsColorHex = "#C8E6C9", backgroundColorHex = "#1B3B1B",
            description = "Verde foresta"),
        ClockStyleDef("Notte stellata", "Tema", false,
            textColorHex = "#E3F2FD", accentColorHex = "#FFD54F",
            secondsColorHex = "#90CAF9", backgroundColorHex = "#0D1433",
            description = "Blu notte con stelle"),
        ClockStyleDef("Lavanda", "Tema", false,
            textColorHex = "#E1BEE7", accentColorHex = "#9C27B0",
            secondsColorHex = "#CE93D8", backgroundColorHex = "#1A0033",
            description = "Lavanda viola"),
        ClockStyleDef("Caffè", "Tema", false,
            textColorHex = "#D7CCC8", accentColorHex = "#8D6E63",
            secondsColorHex = "#A1887F", backgroundColorHex = "#2C1A0E",
            description = "Tonalità caffè calde"),
        ClockStyleDef("Ghiaccio", "Tema", false,
            textColorHex = "#E0F7FA", accentColorHex = "#00ACC1",
            secondsColorHex = "#80DEEA", backgroundColorHex = "#002F35",
            description = "Ghiaccio azzurro"),
        ClockStyleDef("Sabbia", "Tema", false,
            textColorHex = "#FFF3E0", accentColorHex = "#FFB74D",
            secondsColorHex = "#FFCC80", backgroundColorHex = "#3E2723",
            description = "Sabbia del deserto"),
        ClockStyleDef("Vino", "Tema", false,
            textColorHex = "#F8BBD0", accentColorHex = "#C62828",
            secondsColorHex = "#E91E63", backgroundColorHex = "#1A0011",
            description = "Vino rosso scuro"),
        ClockStyleDef("Neon City", "Tema", false,
            textColorHex = "#00FFAA", accentColorHex = "#FF00FF",
            secondsColorHex = "#FFFF00", backgroundColorHex = "#000022",
            showBorderGlow = true,
            description = "Città neon, colori fluorescenti"),

        /* ===== MINIMAL (60-69) ===== */
        ClockStyleDef("Solo ora", "Minimal", false,
            showDate = false, showSeconds = false, fontWeight = 200,
            description = "Solo ore:minuti, nient'altro"),
        ClockStyleDef("Solo secondi", "Minimal", false,
            showDate = false, showSeconds = true, fontWeight = 200,
            secondsColorHex = "#FFFFFF",
            description = "Solo ora e secondi"),
        ClockStyleDef("Data breve", "Minimal", false,
            dateFormat = "d MMM", fontWeight = 300,
            description = "Data in formato breve"),
        ClockStyleDef("Ultra compatto", "Minimal", false,
            showSeconds = false, showDate = false, fontWeight = 700,
            letterSpacing = 0f,
            description = "Massima compattezza, solo ora in grassetto"),
        ClockStyleDef("Grande e chiaro", "Minimal", false,
            timeFontMultiplier = 2.0f, showSeconds = false, showDate = false,
            fontWeight = 100,
            description = "Ora enormi, minimal"),
        ClockStyleDef("Piccolo e preciso", "Minimal", false,
            timeFontMultiplier = 0.6f, showSeconds = true, showDate = true,
            fontWeight = 400,
            description = "Caratteri piccoli, tutto visibile"),
        ClockStyleDef("Solo data", "Minimal", false,
            showSeconds = true, showDate = true, dateFormat = "EEEE",
            fontWeight = 100,
            description = "Giorno della settimana in evidenza"),
        ClockStyleDef("Mono Minimal", "Minimal", false,
            fontFamily = "monospace", showSeconds = false, showDate = false,
            fontWeight = 300,
            description = "Monospace minimal, senza orpelli"),
        ClockStyleDef("Bianco su grigio", "Minimal", false,
            textColorHex = "#FFFFFF", backgroundColorHex = "#1E1E1E",
            showSeconds = false, fontWeight = 300,
            description = "Bianco su grigio scuro"),
        ClockStyleDef("Grigio su nero", "Minimal", false,
            textColorHex = "#AAAAAA", backgroundColorHex = "#000000",
            showSeconds = false, fontWeight = 300,
            description = "Grigio chiaro su nero, sobrio"),

        /* ===== RETRO/VINTAGE (70-79) ===== */
        ClockStyleDef("Vintage Sepia", "Retro", false,
            fontFamily = "serif", textColorHex = "#8B6914",
            accentColorHex = "#A0522D", backgroundColorHex = "#1A1008",
            dateFormat = "d MMMM yyyy",
            description = "Sepia vintage, font serif"),
        ClockStyleDef("Retro Green", "Retro", false,
            fontFamily = "monospace", textColorHex = "#00FF41",
            accentColorHex = "#008F11", backgroundColorHex = "#000800",
            showBorderGlow = true,
            description = "Verde terminale anni 80"),
        ClockStyleDef("Retro Amber", "Retro", false,
            fontFamily = "monospace", textColorHex = "#FFB000",
            accentColorHex = "#FF8C00", backgroundColorHex = "#0A0800",
            description = "Ambra terminale antico"),
        ClockStyleDef("Vintage Roman", "Retro", false,
            fontFamily = "serif", textColorHex = "#D4C5A9",
            accentColorHex = "#C5A55A", backgroundColorHex = "#1A1510",
            dateFormat = "d MMMM yyyy",
            description = "Stile romano antico, pergamena"),
        ClockStyleDef("Retro Digital", "Retro", false,
            fontFamily = "monospace", textColorHex = "#FF4444",
            accentColorHex = "#FF6666", backgroundColorHex = "#1A0000",
            description = "Rosso digitale retro"),
        ClockStyleDef("Vintage Gold", "Retro", false,
            fontFamily = "serif", textColorHex = "#D4AF37",
            accentColorHex = "#B8860B", backgroundColorHex = "#0A0800",
            description = "Oro vintage su nero"),
        ClockStyleDef("Retro Cyan", "Retro", false,
            fontFamily = "monospace", textColorHex = "#00FFFF",
            accentColorHex = "#008888", backgroundColorHex = "#000A0A",
            description = "Ciano retro computer"),
        ClockStyleDef("Vintage Paper", "Retro", false,
            fontFamily = "serif", textColorHex = "#3E2723",
            backgroundColorHex = "#EFEBE0", showAmPm = true,
            description = "Scuro su carta chiara"),
        ClockStyleDef("Retro Scoreboard", "Retro", false,
            fontFamily = "monospace", textColorHex = "#FF6600",
            backgroundColorHex = "#111111", fontWeight = 700,
            description = "Stile tabellone segnapunti"),
        ClockStyleDef("Vintage Elegance", "Retro", false,
            fontFamily = "serif", textColorHex = "#C0A080",
            accentColorHex = "#A08060", backgroundColorHex = "#1A1410",
            fontWeight = 200, dateFormat = "d MMMM yyyy",
            description = "Eleganza vintage"),

        /* ===== GEOMETRIC (80-89) ===== */
        ClockStyleDef("Cerchi", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#4FC3F7",
            analogHandColorHex = "#4FC3F7",
            description = "Geometrico, cerchi e linee"),
        ClockStyleDef("Poligonale", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#FFB74D",
            analogHandColorHex = "#FFB74D", backgroundColorHex = "#0A0A1A",
            description = "Stile poligonale"),
        ClockStyleDef("Triangoli", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#CE93D8",
            analogHandColorHex = "#CE93D8",
            description = "Motivi triangolari"),
        ClockStyleDef("Geometrico blu", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#29B6F6",
            analogHandColorHex = "#29B6F6", backgroundColorHex = "#001A2A",
            description = "Blu geometrico"),
        ClockStyleDef("Geometrico rosso", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#EF5350",
            analogHandColorHex = "#EF5350", backgroundColorHex = "#1A0000",
            description = "Rosso geometrico"),
        ClockStyleDef("Esagonale", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#66BB6A",
            analogHandColorHex = "#66BB6A", backgroundColorHex = "#001A00",
            description = "Verde esagonale"),
        ClockStyleDef("Concentric", "Geometrico", true,
            analogShowNumbers = true, analogTickColorHex = "#FFD54F",
            analogHandColorHex = "#FFD54F",
            description = "Cerchi concentrici"),
        ClockStyleDef("Radiale", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#7E57C2",
            analogHandColorHex = "#7E57C2", backgroundColorHex = "#0A0020",
            description = "Linee radiali"),
        ClockStyleDef("Ottagonale", "Geometrico", true,
            analogShowNumbers = true, analogTickColorHex = "#26C6DA",
            analogHandColorHex = "#26C6DA",
            description = "Motivo ottagonale"),
        ClockStyleDef("Spirale", "Geometrico", true,
            analogShowNumbers = false, analogTickColorHex = "#FF8A65",
            analogHandColorHex = "#FF8A65", backgroundColorHex = "#1A0A00",
            description = "Spirale geometrica"),

        /* ===== EXPERIMENTAL (90-99) ===== */
        ClockStyleDef("Dual Time", "Sperimentale", false,
            dateFormat = "HH:mm", fontWeight = 700, letterSpacing = 2f,
            description = "Ora principale in evidenza"),
        ClockStyleDef("Stacked", "Sperimentale", false,
            dateAboveTime = true, fontWeight = 100, dateFormat = "EEEE\nd MMMM",
            description = "Data impilata sopra l'ora"),
        ClockStyleDef("Roman Numerals", "Sperimentale", true,
            analogShowNumbers = true, analogHandColorHex = "#FFD700",
            analogTickColorHex = "#FFD700",
            description = "Numeri romani (implicitamente)"),
        ClockStyleDef("Binary Touch", "Sperimentale", false,
            fontFamily = "monospace", fontWeight = 300,
            description = "Ispirazione binaria"),
        ClockStyleDef("Weather Focus", "Sperimentale", false,
            showSeconds = false, fontWeight = 200, dateFormat = "EEEE",
            description = "Ora essenziale, focus sul meteo"),
        ClockStyleDef("Music Mode", "Sperimentale", false,
            showSeconds = false, fontWeight = 300, showDate = false,
            description = "Ora pulita per la modalità musica"),
        ClockStyleDef("Glassmorphism", "Sperimentale", false,
            textColorHex = "#FFFFFF", accentColorHex = "#80DEEA",
            backgroundColorHex = "#0A1628",
            description = "Effetto vetro"),
        ClockStyleDef("Holographic", "Sperimentale", false,
            showGradientText = true, showBorderGlow = true,
            backgroundColorHex = "#050510",
            description = "Olografico, gradient + glow"),
        ClockStyleDef("Night Light", "Sperimentale", false,
            textColorHex = "#FF6B35", accentColorHex = "#FF6B35",
            backgroundColorHex = "#1A0500",
            description = "Luce notturna calda"),
        ClockStyleDef("Ultimate", "Sperimentale", false,
            fontWeight = 800, letterSpacing = 8f, showBorderGlow = true,
            textColorHex = "#FFFFFF", backgroundColorHex = "#000000",
            description = "Massimo contrasto, bold, glow")
    )
}
